### PR TITLE
1.0

### LINKED ISSUE #56: Server side rendering checksum error
Hi there is a checksum error when using serverside rendering.. 
 (client) tab" id="react-tabs-0" aria-selected="tr
 (server) tab" id="react-tabs-4" aria-selected="tr

Any ideas what it could be?

### LINKED ISSUE #84: Tabs below content
I want to display the tab content above the tabs, eg:

```
      <Tabs>
        <TabPanel>
          This is content for tab 1
        </TabPanel>
        <TabPanel>
          This is content for tab 2
        </TabPanel>
        <TabPanel>
          This is content for tab 3
        </TabPanel>
        <TabList>
          <Tab>Tab 1</Tab>
          <Tab>Tab 2</Tab>
          <Tab>Tab 3</Tab>
        </TabList>
      </Tabs>
```

Unfortunately, this does not work. Clicking the tabs doesn't do anything.
Is this possible with react-tabs? If yes, how?

### LINKED ISSUE #101: Reduce specificity of default styles
The BEM classes added to each component are super useful for applying custom styling. However, because the default styles have a high specificity (e.g. `.react-tabs [role=tab][aria-selected=true]:hover`), the purpose of adopting BEM is defeated slightly.

I propose using low specificity BEM classes for the default styles, so that they may be overridden more easily

### LINKED ISSUE #125: 1.0 Umbrella
- [x] Remove bower support
- [x] Use ES6 classes
- [ ] Split controlled behavior from non-controlled (#80)
- [ ] Fix isomorphic problems
- [x] Cleanup exports
- [x] Make styling optional

### LINKED ISSUE #135: js-stylesheet issues when used in iframe context
When using react-tabs in tandem with [react-frame-component](https://github.com/ryanseddon/react-frame-component), the tabs end up in the parent document instead of the embedded document.

### LINKED ISSUE #153: Bower version mismatch
The current release is [v0.8.0](https://github.com/reactjs/react-tabs/releases/tag/v0.8.0) but the version in the bower.json file is [0.5.3](https://github.com/reactjs/react-tabs/blob/master/bower.json#L3)

Please update and release versions that are matching.

### LINKED ISSUE #160: React.createClass deprecated
>Warning: Tab: React.createClass is deprecated and will be removed in version 16. Use plain JavaScript classes instead. If you're not yet ready to migrate, create-react-class is available on npm as a drop-in replacement.

### PR DESCRIPTION
**Pull request by danez**
Fixes #160 
Fixes #153
Fixes #135
Fixes #125 
Fixes #56 
Fixes #101
Fixes #84

### CODE REVIEW

**Comment by Hum4n01d** [comment]
Has this been released on NPM?

**Comment by Hum4n01d** [comment]
I don’t think it has. Please take care of this so that we don’t get warnings in the console about `PropTypes` and `createClass`

/cc @danez

**Comment by danez** [comment]
No it hasn't been released yet.

**Comment by Hum4n01d** [comment]
@danez Ok, please release when you get a chance; the warnings in the console are quite annoying 😉

**Pull request merged**
