### PR TITLE
Concatenar classes css com props

### PR DESCRIPTION
**Pull request by LeandroGazoli**
className={cx(DEFAULT_CLASS, className, { // Concatena a classe padrão com a classe existente
        [selectedClassName]: selected,
        [disabledClassName]: disabled,
      })}

Recomendação de alteração para concatenar classes sem perde o default

### CODE REVIEW

**Review by musllim — COMMENTED** [review]
I think this is good idea

**Comment by LeandroGazoli** [comment]
I believe this helps a lot.
In my case I made this change in my system it worked very well.

**Review by musllim — APPROVED** [review]
LGTM

className from defaultProps is being overwritten by className from props.

**Comment by danez** [comment]
We do no concatenate on purpose, because if you are not using the default css and want to use your own classnames.

We could export the default classnames as constants, so the can be concatenated in your code?

**Pull request closed without merging**
