### PR TITLE
Allow for higher order components

### PR DESCRIPTION
**Pull request by karevn**

### CODE REVIEW

**Comment by danez** [comment]
This looks awesome and would solve #187 and #148.

Could you add a simple testcase that shows the hoc work?

**Comment by karevn** [comment]
OK, no prob.

**Comment by mrmohtas** [comment]
@danez Is this suitable for merging? Would be great to have this if it solves the styled-components issue

**Comment by karevn** [comment]
@danez any input? It's hanging here for almost 3 weeks.

**Comment by danez** [comment]
I added a test to see if it works with `hoist-non-react-statics` and it works :). Means that redux, stylecomponents, recompose and some more will work out of the box without even setting `tabsRole`.

Thank you very much.

**Pull request merged**
