### PR TITLE
Remove rackt-cli

### PR DESCRIPTION
**Pull request by chentsulin**
This project has been moved from rackt to reactjs org, so I think removing `rackt-cli` is something that eventually need to be done. And then after merged this, we can move forward to clean up some stuffs and update some dependencies which we care (babel 6, eslint 2, react 15). At this moment, neither react-tabs nor react-simple-tabs support react v15. 

@timdorr @mzabriskie This PR now pass the tests. webpack, eslint, karma configs and scirpts is copies from react-cli repo, and we can refactor them later.

### CODE REVIEW

**Comment by danez** [comment]
I already have a branch locally that is doing the same and uses eslint2 and jest for the tests. I'm gonna merge this branch as soon as all tests pass. And then iterate on the remaining issues.

**Comment by chentsulin** [comment]
Is there any reasons or advantages that make we migrate tests from mocha to jest? I think support v15 is our highest priority.

**Comment by danez** [comment]
I wanted to have the tests running before starting to fix other stuff, but you are right, that react 15 is now the highest priority.

**Comment by chentsulin** [comment]
https://travis-ci.org/reactjs/react-tabs/jobs/134950549

There is already 25 tests run on travis's Firefox via mocha and karma. Are they enough for fix other stuff or they don't cover all testing cases we need?

**Comment by danez** [comment]
Done in #100

**Pull request closed without merging**
