### PR TITLE
Support custom ID generators for elements

### LINKED ISSUE #56: Server side rendering checksum error
Hi there is a checksum error when using serverside rendering.. 
 (client) tab" id="react-tabs-0" aria-selected="tr
 (server) tab" id="react-tabs-4" aria-selected="tr

Any ideas what it could be?

### PR DESCRIPTION
**Pull request by neeharv**
Fixes #56 

This is still work in progress. I need to add tests and figure out if this is a viable fix for this problem.

### CODE REVIEW

**Comment by ads1018** [comment]
Looking to use this component in my universal app as well. Would love to get this merged in!

**Comment by neeharv** [comment]
I haven't heard anything on this yet, so in the meanwhile I've released
https://www.npmjs.com/package/react-tabs-isomorphic so I can start using
this in production with an isomorphic app. I'll update the pr over the
weekend with some more tweaks, but till then, anyone who wants to get it
working server side can use that lib.

**Comment by pr1ntr** [comment]
If this works why not merge? It has been a few months.

**Comment by danez** [comment]
Instead of allowing a custom generator function, I went for a static function which allows to reset the internal counter in 88721f8ef4a63cdf595c12dd3876131bd91ccd53

**Pull request closed without merging**
