### PR TITLE
Fix nested Tabs (Issue #54)

### PR DESCRIPTION
**Pull request by msliberty**
This patch assumes that the Tab node will always be the grandchild of the Tabs component node.

### CODE REVIEW

**Comment by mzabriskie** [comment]
Will you update your PR to not include the changes in `dist/`?

**Comment by jamesaevans** [comment]
Would appreciate a merge here, if convenient. Thanks!

**Comment by rfreling** [comment]
Would also appreciate a merge. Thanks!

**Comment by joepvl** [comment]
I'd like to use nested tabs in a project and am looking for some clarity on this PR. @mzabriskie would you like @msliberty to rebase so the changes to `dist/` don't show up in the repo history or are you fine merging this as it is and just haven't gotten around to it?

**Comment by msliberty** [comment]
Sorry about that. I have rebased my PR onto the latest master. The tests pass locally; I'm not sure why it's failing on Travis.

Let me know if there's anything else I can do :)

**Comment by joepvl** [comment]
@msliberty apparently there's a problem with [mzabriskie/rackt-cli](https://github.com/mzabriskie/rackt-cli) and npm 3.x (see issues in that repo for more info). That needs to be fixed first, the package updated on npm, and the dep updated in this repo, before the tests will pass again on Travis CI.
Alternatively, perhaps changing the Node version to `4` in .travis.yml would work as a temp fix? I'm not sure if builds were universally broken before it was set to `5`. I'll check that out.

**Comment by callmephilip** [comment]
i can confirm that this fixes the problem. would appreciate the merge. thanks @msliberty!

**Comment by kirankashalkar** [comment]
Please merge. Thanks @msliberty

**Comment by danez** [comment]
closing in favor of #91. Thanks.

**Pull request closed without merging**
