### PR TITLE
Fix nested tabs issue #54

### PR DESCRIPTION
**Pull request by happycollision**
This builds off of @msliberty's PR #61

This one, however, doesn't assume that "that the Tab node will always be the grandchild of the Tabs component node". Just that it will be a descendant. Feedback is welcome.

### CODE REVIEW

**Comment by degr** [comment]
+1

**Comment by danez** [comment]
Thanks for your PR this is now fixed as of 9b5eeae

**Comment by kirankashalkar** [comment]
Is this now fixed in the current version?

**Comment by joepvl** [comment]
@kirankashalkar yep, it is! 😄

**Comment by kirankashalkar** [comment]
What version is this exactly fixed in?
0.5.5?

**Pull request closed without merging**
